version: "3.8"
services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: flightbookdb
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql-data:/var/lib/mysql

  flight-api:
    build: .
    container_name: flight-api
    # depends_on:
    #   - mysql
    ports:
      - "8080:8080"
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/flightbookdb
    #   SPRING_DATASOURCE_USERNAME: root
    #   SPRING_DATASOURCE_PASSWORD: 123456
    #   SPRING_JPA_HIBERNATE_DDL_AUTO: update
    #   SPING_SQL_INIT_MODE: always
# volumes:
#   mysql-data:
