server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: flightApi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flightbookdb
    username: root
    password: 123456
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 50
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.example.flightapi.controller

    
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
